version: '3.1'

services:

  db:
    build: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dis_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
  web:
    build: test-project
    restart: always
    ports:
      - 8080:8080
  # server:
  #   build: server
  #   ports:
  #     - 8081:8081
